steps:
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: | 
      **/*.[Tt]ests.*.csproj
      !**/*.IntegrationTests.*.csproj
    arguments: '--configuration Release'